name: Build and Deploy Java WAR Project

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request: # Optional: Trigger on pull requests
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Build the WAR file with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Log in to Docker Hub (if publishing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-app-name:latest .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/your-app-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Step 1: Pull and run the Docker container (example for a self-hosted server)
      - name: Pull and Run Docker Container
        run: |
          docker pull your-dockerhub-username/your-app-name:latest
          docker run -d -p 8080:8080 your-dockerhub-username/your-app-name:latest
