name: Java CI Build
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
 
      # Step 3: Cache Maven dependencies (Optional for faster builds)
      #- name: Cache Maven packages
       # uses: actions/cache@v3
        #with:
         # path: ~/.m2/repository
          #key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          #restore-keys: |
           # ${{ runner.os }}-maven-
 
      # Step 4: Build the project using Maven
      #- name: Build with Maven
      #  run: mvn clean install

      - name: Build project with Maven
        run: mvn -B package --file pom.xml
 
      # Step 5: Run tests
      #- name: Run tests with Maven
       # run: mvn test
    
