name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 (or other version as needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Cache Maven packages
      #- name: Cache Maven packages
       # uses: actions/cache@v2
       # with:
         # path: ~/.m2/repository
        #  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         # restore-keys: |
          #  ${{ runner.os }}-maven-

      #- name: SonarQube Scan
       # env:
          # SONAR_TOKEN: ${{ secrets.DEMO }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
       # run: |
         # mvn clean verify sonar:sonar \
          #  -Dsonar.projectKey=your_project_key \
           # -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
           # -Dsonar.login=${{ secrets.SONAR_TOKEN }}   
            

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Upload the built artifact (e.g., a JAR or WAR file)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: target/*.war  # or *.war if it's a WAR file

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the artifact uploaded from the previous job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-artifact
          path: ./artifact

      # Deploy to the web server
      # You can customize the deployment process based on your setup. This example deploys to an Azure Web App.
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-webapp-name"    # Replace with your Azure web app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./artifact/*.jar        # or *.war

 
